# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b6517fad97a7d1dda91738a138480f750b05fe17f1800e5d527a7507f728b945165c677055111432128e438e4096ca0b4eab3c6f87e354827903f1894839e8f

test:
  secret_key_base: 393c76be606f5f10c061c01b71c271c6f0348abecae9f87078d6ea8229c1b2581695b583eec2a2e2148aeaaf2f8d7a4af8dde4c533054f53a0c09eced33144a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
